### ISSUE TITLE
Bug in parsing '@' in comment paragraphs

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/rehash#292]
Comments: When an `@` symbol is followed by a space, that space disappears if there is a hyperlink later in the same paragraph.

The bug is documented in this thread: https://soylentnews.org/comments.pl?sid=14988&cid=387660

Reproduced here: https://soylentnews.org/comments.pl?sid=14988&cid=387665

**Comment by marty-b** [comment]
ISTR that TheMightyBuzzard implemented a feature quite a while ago to permit a commenter to reference a user nick/UID in a comment and have that reference change into a URL pointing to that nick's userinfo page on the site.  I tried to remember the syntax and made some attempts on the dev server, but it did not seem to work. 
See: https://dev.soylentnews.org/comments.pl?noupdate=1&sid=1282&cid=28835#commentwrap

**Comment by marty-b** [comment]
I was close... "@nickname:" will convert to a reference to a user's info page.  The trailing colon is required so as to bracket user nicks which are permitted to *include* spaces. Such as:
   @The Mighty Buzzard:
See: TMB's reply: 
   https://dev.soylentnews.org/comments.pl?noupdate=1&sid=1282&cid=28836#commentwrap
And a quick test with 3 variations:
   @martyb:
   @martyb :
   @ martyb:
can be see on dev, here:
   https://dev.soylentnews.org/article.pl?sid=16/07/24/2353241&commentsort=0&mode=thread&noupdate=1#comment_28837

**Comment by soytakyon** [comment]
I think we can all agree that there are no valid usernames in the database that start with a space. Therefore, "@ blahblah" should not trigger the nick code and this is still a bug.

**Comment by TheMightyBuzzard** [comment]
Fixed in #299

**Comment by paulej72** [comment]
Not fixed fully.  If you put in @12:34 you get @12:4 in a comment.  the @Nick: will eat the next char after the :.  Need to fix the regex.

**Comment by paulej72** [comment]
Think I got it in #365

**Comment by paulej72** [comment]
fixed
